language: node_js
node_js:
    - 'stable'
cache:
    directories:
        - node-modules
script:
    - yarn test --watchAll=false
on:
    branch: master
deploy:
    provider: heroku
    api_key: $HEROKU_KEY
    app: $HEROKU_APP